name: Codestyle Checks
on:
  push:
  pull_request:

jobs:
  check-codestyle:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Check Codestyling
    steps:
      - uses: actions/checkout@v3
      - name: Check Codestyling
        run: source ./apps/ci/ci-codestyle.sh
